# Generated by Django 4.2.20 on 2026-02-15 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyCheckinSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkin_password",
                    models.CharField(
                        help_text="学生访问打卡页面所需密码",
                        max_length=128,
                        verbose_name="打卡页面密码",
                    ),
                ),
                (
                    "summary_password",
                    models.CharField(
                        help_text="访问统计汇总页面所需密码",
                        max_length=128,
                        verbose_name="统计页面密码",
                    ),
                ),
                (
                    "daily_target_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        help_text="达到此时长后显示提醒",
                        max_digits=4,
                        verbose_name="每日学习目标(小时)",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习打卡设置",
                "verbose_name_plural": "学习打卡设置",
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="会话标识"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="实际学习时长（扣除暂停时间）",
                        verbose_name="学习时长(秒)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "学习记录",
                "verbose_name_plural": "学习记录",
                "ordering": ["-start_time"],
            },
        ),
    ]
