# Generated by Django 4.2.20 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_checkin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="今日总结"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "每日总结",
                "verbose_name_plural": "每日总结",
                "ordering": ["-date"],
            },
        ),
    ]
